name: Build Windows Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSYS2 environment
        uses: msys2/setup-msys2@v2

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm mingw-w64-x86_64-toolchain
          pacman -S --needed --noconfirm mingw-w64-x86_64-cmake
          pacman -S --needed --noconfirm mingw-w64-x86_64-pkg-config
          pacman -S --needed --noconfirm mingw-w64-x86_64-openssl

      - name: Configure and build
        run: |
          mkdir -p build
          cd build
          cmake -G "MinGW Makefiles" ..
          cmake --build .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: build/idevicebackup2.exe
